### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nguyenduyhieukma** [cryptosubtlety/intuitive-advanced-cryptography#3]
Hi Quan,

In section 9 (page 14), you wrote:

> The pairing that we use has a few nice properties such as: `e(P + Q, R) =
e(P, R) + e(Q, R) and e(a.P, b.Q) = e(P, Q)^(a*b)`

Maybe you meant:
-   `e(P + Q, R) =
e(P, R) * e(Q, R) and e(a.P, b.Q) = e(P, Q)^(a*b)`, as `^` denotes repeated `*`.
-   or `e(P + Q, R) = e(P, R) + e(Q, R) and e(a.P, b.Q) = e(P, Q).(a*b)`, as `.` denotes repeated `+`.

**Comment by nguyenduyhieukma** [comment]
And `a`, `b` should be integers also (not elements of `F`).

**Comment by nguyenduyhieukma** [comment]
In section 9.1 (page 15), I think the problem is reduced to DLP over the finite field F (not the set of integers).

**Comment by cryptosubtlety** [comment]
Good catch, thanks Hieu :) Please reopen if the latest version doesn't fix your comment.
