### ISSUE TITLE
Lattice section -> prime modulus

### ISSUE THREAD

**Issue by Pro7ech** [cryptosubtlety/intuitive-advanced-cryptography#4]
Hello, 

In the lattice section, the coefficient modulus (q) is always stated to be prime (I guess it was taken from the shell implementation), but it does not need to be prime. It can in fact be any integer as long as it is smaller than the maximum bitsize for a given ring degree to ensure security. 

Being prime has no effect on the security at all (although from recent research the structure of Q might lead to very efficient quantum attacks). It can however enable more efficient implementations (like RNS representation and the usage of the NTT) and sometime you do not want it to be prime, for example the official HEAAN implementation use q = 2^s (a power of two).

**Comment by cryptosubtlety** [comment]
Thanks for pointing this out :) I removed "prime modulus" in the general section of lattice based cryptography, but kept it in shell section.
